apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: taskapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: ghcr.io/ts-a-devops/taskapp-backend:5d6b8fc
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: taskapp-config
        - secretRef:
            name: taskapp-secrets
